sudo: true
language: python
python:
  - "3.5"
before_install:
 - bash ci/libsodium.sh
install:
 - pip install coveralls
 - pip install -r requirements.txt
# command to run tests
script:
 - coverage run --source=ucoinpy setup.py test
after_success:
 - coveralls